goroutine:
  max-goroutine: 2000 #goroutine池最大线程数
  core-goroutine: 1000  #goroutine池核心线程数
  timeout: 5 #goroutine池等待超时时间 单位秒

Themis:
  port: 50000  #注册中心http端口
  UDP-port: 12345 #UDP服务端口  -- 与客户端需要对应
  UDP-timeout: 5 #UDP服务超时时间 单位秒

  server:
    model-queue: 100  #服务注册处理队列容量
    model-handle-number: 2 #服务注册处理协程数量

    beat-enable: true #是否开启心跳
    beat-queue: 200 #服务心跳处理队列容量
    beat-time: 15  #服务心跳超时时间   单位秒

  leader-algorithm: RandomAlgorithmCreateLeader #记账人选举算法
  election-timeout: 10 #选举超时时间 单位秒

  database:
    enable: false  #是否开启持久化
    persistence-time: 10 #持久化间隔 单位秒
    soft-delete-enable: true #是否开启软删除
    type: mysql #数据库选型  mysql/sqllit

    mysql:
      host: 192.168.71.128 #数据库地址
      port: 3306 #数据库端口
      user: root #数据库用户名
      password: 2167137570legacy #数据库密码
      name: themis #数据库名称
      max-open-conns: 10 #数据库最大连接数
      max-idle-conns: 10 #数据库最大空闲连接数
      max-conns-lifetime: 10 #数据库连接最大存活时间 单位秒

  listen:
    space-time: 10 #监控间隔时间

  #集群配置
  cluster:
    enable: false #是否开启集群
    track-enable: false #是否开启集群数据跟踪
    name: themis-A #集群名称
    ip: localhost #ip地址
    port: 8080 #集群端口
    max-follow-timeout: 10 #raft-follow最大超时时间 单位秒
    min-follow-timeout: 5  #raft-follow最小超时时间 单位秒
    max-candidate-timeout: 10 #raft-candidate最大超时时间 单位秒
    min-candidate-timeout: 5 #raft-candidate最小超时时间 单位秒
    leader-snapshot-sync-time: 5 #集群leader-snapshot同步时间 单位秒
    leader-heartbeat-time: 1000 #集群leader-heartbeat时间 单位毫秒
    leader-queue: 100 #集群leader-queue队列容量
    udp-timeout: 10 #UDP超时时间 单位秒
    udp-queue-num: 100 #集群处理队列容量
    clusters: #集群列表
      - ip: localhost
        port: 8081
      - ip: localhost
        port: 8082
    enable-encryption: false #是否开启加密
    encryption-key: DIS**#KKKDJJSKDI #加密key