// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.wzxaugenstern.online/#/",
        "contact": {
            "name": "Karenina-na",
            "url": "https://www.wzxaugenstern.online/#/",
            "email": "weizixiang0@outlook.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/message/follow/getLeader": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由其他服务调用的获取当前领导者接口。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "获取领导者",
                "parameters": [
                    {
                        "description": "非领导者实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回领导者服务信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.ServerModel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/message/follow/getServers": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由当前领导者调用的获取领导者所领导的服务列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "获取当前被领导者服务列表",
                "parameters": [
                    {
                        "description": "领导者实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回被领导者的切片数组",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.ServerModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/message/follow/getServersNum": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由所有服务调用获取当前集群服务数量。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "获取当前集群服务数量",
                "parameters": [
                    {
                        "description": "服务实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回集群服务数量",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/message/leader/beat": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务心跳重置倒计时",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "服务心跳",
                "parameters": [
                    {
                        "description": "服务实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/message/leader/election": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由领导者调用的新一轮选举接口。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "选举",
                "parameters": [
                    {
                        "description": "领导者或非领导者服务实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/message/leader/register": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务注册进中心",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "服务注册",
                "parameters": [
                    {
                        "description": "服务实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/message/manager/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "管理员登录接口。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务层"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "管理员账号密码",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Root"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回token",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/blacklistColony": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用删除地区集群实例并拉入黑名单。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "删除地区集群实例并拉入黑名单",
                "parameters": [
                    {
                        "description": "被删除的服务地区信息（用服务实例信息包装）",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/blacklistInstance": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用删除服务实例并拉入黑名单。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "删除服务实例并拉入黑名单",
                "parameters": [
                    {
                        "description": "被删除的服务实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/blacklistNamespace": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用删除地区集群实例并拉入黑名单。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "删除命名空间集群实例并拉入黑名单",
                "parameters": [
                    {
                        "description": "被删除的服务命名空间信息（用服务实例信息包装）",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/deleteBlacklistInstance": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用删除黑名单中的实例信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "删除黑名单中的实例信息",
                "parameters": [
                    {
                        "description": "从黑名单中清除的实例信息",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回true或false",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/getBlacklist": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用的获取当前全部黑名单服务实例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取全部黑名单服务实例",
                "responses": {
                    "200": {
                        "description": "返回黑名单中服务实例切片数组",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.ServerModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/CURD/getColonies": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取指定命名空间下的集群",
                "responses": {
                    "200": {
                        "description": "返回集群列表名称",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/CURD/getColoniesInstances": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取指定命名空间下的集群和服务名",
                "responses": {
                    "200": {
                        "description": "返回集群服务列表名称",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/CURD/getInstance": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用的获取指定服务信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取服务实例",
                "responses": {
                    "200": {
                        "description": "返回服务封装",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/getInstances": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用的获取当前所有服务信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取全部服务实例",
                "responses": {
                    "200": {
                        "description": "返回服务全体封装",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/CURD/getInstancesByCondition": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取命名空间与集群条件下的服务实例。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取指定条件下的服务实例服务实例--模糊查询",
                "parameters": [
                    {
                        "description": "封装的条件参数",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回服务实例切片数组",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.ServerModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/CURD/getInstancesByConditionMap": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取命名空间与集群条件下的服务实例。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取指定条件下的服务实例服务实例--精确查询",
                "parameters": [
                    {
                        "description": "封装的条件参数",
                        "name": "Model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ServerModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回服务实例map切片数组",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "array",
                                                "items": {
                                                    "$ref": "#/definitions/entity.ServerModel"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/CURD/getNamespaces": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理者调用的获取当前所有服务信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取全部命名空间",
                "responses": {
                    "200": {
                        "description": "返回命名空间列表名称",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/cluster/getClusterLeader": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理员调用获取中心集群领导者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取中心集群领导者",
                "responses": {
                    "200": {
                        "description": "返回中心集群领导者名称",
                        "schema": {
                            "$ref": "#/definitions/entity.ResultModel"
                        }
                    }
                }
            }
        },
        "/operator/cluster/getClusterStatus": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理员调用获取中心当前身份状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取中心当前身份状态",
                "responses": {
                    "200": {
                        "description": "返回集群状态",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/operator/cluster/getStatus": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "由管理员调用获取当前中心服务器状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理层"
                ],
                "summary": "获取服务器状态",
                "responses": {
                    "200": {
                        "description": "返回电脑状态",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.ResultModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.ComputerInfoModel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.ComputerInfoModel": {
            "type": "object",
            "properties": {
                "cpu_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CpuInfoModel"
                    }
                },
                "disk_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.DiskInfoModel"
                    }
                },
                "host_info": {
                    "$ref": "#/definitions/entity.HostInfoModel"
                },
                "mem_info": {
                    "$ref": "#/definitions/entity.MemInfoModel"
                },
                "net_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.NetInfoModel"
                    }
                },
                "pool_activate_num": {
                    "type": "integer"
                },
                "pool_job_num": {
                    "type": "integer"
                }
            }
        },
        "entity.CpuInfoModel": {
            "type": "object",
            "properties": {
                "cpu_core_num": {
                    "type": "string"
                },
                "cpu_frequency": {
                    "type": "string"
                },
                "cpu_name": {
                    "type": "string"
                },
                "cpu_physical_id": {
                    "type": "string"
                },
                "cpu_usage": {
                    "type": "string"
                },
                "cpu_vendor_id": {
                    "type": "string"
                }
            }
        },
        "entity.DiskInfoModel": {
            "type": "object",
            "properties": {
                "disk_avi": {
                    "type": "string"
                },
                "disk_name": {
                    "type": "string"
                },
                "disk_size": {
                    "type": "string"
                },
                "disk_usage": {
                    "type": "string"
                },
                "disk_used": {
                    "type": "string"
                },
                "fs_type": {
                    "type": "string"
                },
                "opts": {
                    "type": "string"
                }
            }
        },
        "entity.HostInfoModel": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "string"
                },
                "host_kernel_arch": {
                    "type": "string"
                },
                "host_kernel_version": {
                    "type": "string"
                },
                "host_name": {
                    "type": "string"
                },
                "host_os": {
                    "type": "string"
                },
                "host_os_version": {
                    "type": "string"
                }
            }
        },
        "entity.MemInfoModel": {
            "type": "object",
            "properties": {
                "mem_avi": {
                    "type": "string"
                },
                "mem_total": {
                    "type": "string"
                },
                "mem_usage": {
                    "type": "string"
                },
                "mem_used": {
                    "type": "string"
                }
            }
        },
        "entity.NetInfoModel": {
            "type": "object",
            "properties": {
                "bytes_received": {
                    "type": "string"
                },
                "bytes_sent": {
                    "type": "string"
                },
                "net_name": {
                    "type": "string"
                },
                "packets_received": {
                    "type": "string"
                },
                "packets_sent": {
                    "type": "string"
                }
            }
        },
        "entity.ResultModel": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.Root": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "entity.ServerModel": {
            "type": "object",
            "properties": {
                "IP": {
                    "type": "string"
                },
                "colony": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "udp_port": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Themis",
	Description:      "分布式记账系统调度中心",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
